/** Turkish UI strings, keyed by the English text. Missing keys fall back to English. */
export const tr: Record<string, string> = {
  '"Break-even" is how many more orders you need to earn the same total profit as today.': '"Başa baş", bugünkü toplam kârı yakalamak için ne kadar fazla sipariş gerektiğini gösterir.',
  '"Break-even" is the share of customers who must change their order for the campaign to beat doing nothing. Lower is safer.': '"Başa baş", kampanyanın hiçbir şey yapmamaktan iyi olması için siparişini değiştirmesi gereken müşteri oranıdır. Düşük olan daha güvenlidir.',
  '% off': '% indirim',
  '% off each unit': 'Adet başı % indirim',
  '% off the cart': 'Sepette % indirim',
  '+1 unit': '+1 adet',
  '1. What are you aiming for?': '1. Hedefiniz ne?',
  '2. Your customers today': '2. Bugünkü müşterileriniz',
  '3. Limits': '3. Sınırlar',
  'A discount on single units costs you on every order, including customers who would have bought anyway. The result shows how many extra orders you need to earn the same as today.': 'Tek ürüne indirim, zaten alacak olan müşteriler dahil her siparişte size maliyet yaratır. Sonuç, bugünkü kazancı yakalamak için kaç ek sipariş gerektiğini gösterir.',
  'Add': 'Ekle',
  'Add and turn on': 'Ekle ve aç',
  'Add box': 'Kutu ekle',
  'Add one': 'Bir tane ekle',
  'Add product': 'Ürün ekle',
  'Add row': 'Satır ekle',
  'Add step': 'Kademe ekle',
  'Add-on product': 'Ek ürün',
  'Added to the shipping tariff': 'Kargo tarifesine eklenir',
  'All products': 'Tüm ürünler',
  'Also try product + cart campaign pairs': 'Ürün + sepet kampanyası ikililerini de dene',
  'An order goes in the smallest box that fits. Above the largest box it ships as several boxes, billed on total desi. Packaging is your cost per box (box, tape, label), VAT included.': 'Sipariş sığdığı en küçük kutuya konur. En büyük kutuyu aşarsa birden çok kutuyla gönderilir ve toplam desi üzerinden ücretlendirilir. Paketleme, kutu başına maliyetinizdir (kutu, bant, etiket), KDV dahil.',
  'Applied': 'Uygulanan',
  'Applies to': 'Geçerli ürünler',
  'At {q} pcs the order reaches free shipping and you stop collecting the shipping fee. Unit {q} lowers profit by {d} TL, so {prev} pcs earn more than {q}.': '{q} adette sipariş ücretsiz kargoya ulaşır ve kargo ücreti alınmaz. {q}. adet kârı {d} TL düşürür; yani {prev} adet, {q} adetten fazla kazandırır.',
  'At {q} pcs the order reaches free shipping and you stop collecting the shipping fee. Unit {q} still adds {d} TL.': '{q} adette sipariş ücretsiz kargoya ulaşır ve kargo ücreti alınmaz. {q}. adet yine de {d} TL ekler.',
  'At {r} response': '{r} yanıtla',
  'Average profit per order today: {x} TL': 'Bugün sipariş başına ortalama kâr: {x} TL',
  'Bigger baskets': 'Daha büyük sepetler',
  'Box': 'Kutu',
  'Box slots per unit': 'Adet başı kutu yeri',
  'Boxes and packaging': 'Kutular ve paketleme',
  'Break-even': 'Başa baş',
  'Break-even compares average profit per order across your customer mix: today with no campaign, against the campaign when a share of customers moves to the target order. Discounts given to customers who would have bought anyway count as a cost.': 'Başa baş, müşteri dağılımınıza göre sipariş başı ortalama kârı karşılaştırır: bugünkü kampanyasız hal ile müşterilerin bir kısmı hedef siparişe geçtiğindeki kampanyalı hal. Zaten alacak olan müşterilere verilen indirim maliyet sayılır.',
  'Build an order': 'Sipariş oluştur',
  'Bundle price': 'Paket fiyatı',
  'Bundles of {sizes} pcs fill a box exactly, so the last units ship at no extra cost.': '{sizes} adetlik paketler bir kutuyu tam doldurur; son adetler ek kargo maliyeti yaratmaz.',
  'Buy': 'Al',
  'Buy X pay Y': 'X al Y öde',
  'Buy {b} pay {p}': '{b} al {p} öde',
  'By quantity': 'Adede göre',
  'Campaign': 'Kampanya',
  'Campaign lab': 'Kampanya laboratuvarı',
  'Campaigns': 'Kampanyalar',
  'Campaigns on this order': 'Bu siparişteki kampanyalar',
  'Campaigns that are on': 'Açık kampanyalar',
  'Cancel': 'Vazgeç',
  'Cart campaigns': 'Sepet kampanyaları',
  'Cart discount': 'Sepet indirimi',
  'Cart over': 'Sepet tutarı en az',
  'Cart tiers': 'Sepet kademeleri',
  'Change': 'Değiştirilecek',
  'Collapse': 'Daralt',
  'Columns': 'Sütunlar',
  'Combinations': 'Birleştirme kuralları',
  'Commission': 'Komisyon',
  'Copied to clipboard.': 'Panoya kopyalandı.',
  'Copy as text': 'Metin olarak kopyala',
  "Copy this zone's prices to all zones": 'Bu bölgenin fiyatlarını tüm bölgelere kopyala',
  'Cost': 'Maliyet',
  'Cost of goods': 'Ürün maliyeti',
  'Costs': 'Maliyetler',
  'Cross-sell': 'Çapraz satış',
  'Custom': 'Özel',
  'Customer pays': 'Müşteri öder',
  'Customer saves between': 'Müşterinin kazancı',
  'Customers who buy one or two buy enough to fill a box.': 'Bir iki adet alan müşteriler bir kutuyu dolduracak kadar alsın.',
  'Customers who buy one product add the other.': 'Bir ürünü alan müşteri diğerini de eklesin.',
  'Customers you expect to respond': 'Yanıt vermesini beklediğiniz müşteri',
  'Deduct VAT payable from profit. Off: profit is shown with VAT included and VAT is tracked separately.': "Ödenecek KDV'yi kârdan düş. Kapalıyken kâr KDV dahil gösterilir, KDV ayrıca takip edilir.",
  'Delete': 'Sil',
  'Delete this campaign?': 'Bu kampanya silinsin mi?',
  'Desi': 'Desi',
  'Discount': 'İndirim',
  'Discounts': 'İndirimler',
  'Duplicate': 'Kopyala',
  'EPH': 'EPH',
  'Each campaign on its own': 'Her kampanya tek başına',
  'Edit': 'Düzenle',
  'Every Nth unit': 'Her N. adet',
  'Every Nth unit off': 'Her N. adede indirim',
  'Every combination of two products in one order, with all campaigns that are on. Hover a cell for details.': 'İki ürünün tek siparişteki tüm kombinasyonları, açık kampanyalarla. Ayrıntı için hücrenin üzerine gelin.',
  'Every order size for one product. Click a column group to expand or shrink it. Rows where one more unit lowers profit are marked red.': 'Bir ürün için her sipariş adedi. Sütun grubuna tıklayarak genişletin ya da daraltın. Bir adet daha eklemenin kârı düşürdüğü satırlar kırmızıdır.',
  'Every saved campaign tested alone against no campaign. Switch one on to use it everywhere.': 'Kayıtlı her kampanya, kampanyasız duruma karşı tek başına denenir. Her yerde kullanmak için açın.',
  'Every {n}. unit free': 'Her {n}. adet bedava',
  'Everything saves automatically in this browser. Export a file to keep a backup or to open the same setup on another computer.': 'Her şey bu tarayıcıya otomatik kaydedilir. Yedek almak veya aynı kurulumu başka bir bilgisayarda açmak için dosyaya aktarın.',
  'Expand': 'Genişlet',
  'Export file': 'Dosyaya aktar',
  'Exported.': 'Dışa aktarıldı.',
  'Extra costs such as shipping are the most common reason shoppers abandon a cart. Many shoppers add items to qualify for free shipping, and thresholds a little above the usual order work best.': 'Kargo gibi ek maliyetler, sepetin terk edilmesinin en yaygın nedenidir. Birçok müşteri ücretsiz kargo için sepetine ürün ekler; alt sınırın olağan siparişin biraz üstünde olması en iyi sonucu verir.',
  'Fees and VAT': 'Ücretler ve KDV',
  'Free shipping': 'Ücretsiz kargo',
  'Free shipping applies, so you pay the whole shipping cost.': 'Kargo ücretsiz; kargo maliyetinin tamamını siz ödersiniz.',
  'Free shipping from': 'Ücretsiz kargo alt sınırı',
  'Free shipping over {a} TL': '{a} TL üzeri kargo bedava',
  'Free shipping starts at {q} pcs ({x} TL).': 'Ücretsiz kargo {q} adetten başlar ({x} TL).',
  'From': 'Başlangıç',
  'From qty': 'En az adet',
  'Gross margin': 'Brüt marj',
  'Hide campaigns': 'Kampanyaları gizle',
  'Holds': 'Kapasite',
  'How orders of this product split by quantity today. Guess if you are not sure; the ranking holds up well.': 'Bu ürünün siparişlerinin bugün adede göre dağılımı. Emin değilseniz tahmin edin; sıralama pek değişmez.',
  'Ideas': 'Fikirler',
  'If nobody responds': 'Kimse yanıt vermezse',
  'Import file': 'Dosyadan yükle',
  'It is deducted from the profit above.': 'Yukarıdaki kârdan düşülmüştür.',
  'It is not deducted from the profit above. You can change that in Products & costs.': 'Yukarıdaki kârdan düşülmemiştir. Bunu Ürünler ve maliyetler sekmesinden değiştirebilirsiniz.',
  'Keep these prices': 'Bu fiyatları kaydet',
  'Large': 'Büyük',
  'Left out by combination rules': 'Birleştirme kuralları nedeniyle uygulanmadı',
  'List price': 'Liste fiyatı',
  'Load': 'Yükle',
  'Load pasted text': 'Yapıştırılan metni yükle',
  'Loaded.': 'Yüklendi.',
  'Margin': 'Marj',
  'Margin by quantity': 'Adede göre marj',
  'Maximum saving': 'En çok kazanç',
  'Medium': 'Orta',
  'Minimum margin on the target order': 'Hedef siparişte en düşük marj',
  'Minimum saving': 'En az kazanç',
  'Mixed orders': 'Karışık siparişler',
  'More visitors buy at all, even a single unit.': 'Daha çok ziyaretçi, tek adet bile olsa alışveriş yapsın.',
  'Most expected profit': 'En yüksek beklenen kâr',
  'Most profit on the target order': 'Hedef siparişte en yüksek kâr',
  'Name': 'Ad',
  'Name for the campaigns that are on': 'Açık kampanyalar için ad',
  'Never pays off': 'Hiç karşılamaz',
  'New box': 'Yeni kutu',
  'New campaign': 'Yeni kampanya',
  'New unit price': 'Yeni adet fiyatı',
  'No campaign': 'Kampanyasız',
  'No campaigns for this product yet.': 'Bu ürün için henüz kampanya yok.',
  'No campaigns yet. Add one to see its effect on every result.': 'Henüz kampanya yok. Etkisini tüm sonuçlarda görmek için bir tane ekleyin.',
  'Not applied because of combination rules: {list}. The customer gets the combination that saves them the most.': 'Birleştirme kuralları nedeniyle uygulanmadı: {list}. Müşteriye en çok kazandıran kombinasyon uygulanır.',
  'Nothing meets these limits. Lower the minimum margin or the minimum saving.': 'Bu sınırlara uyan kampanya yok. En düşük marjı veya en az kazancı düşürün.',
  'Off each unit': 'Adet başı indirim',
  'On': 'Açık',
  'On products after discounts': 'İndirimlerden sonraki ürün tutarı üzerinden',
  'On top of the campaigns that are on': 'Açık kampanyaların üzerine',
  'Or paste saved text here': 'Ya da kayıtlı metni buraya yapıştırın',
  'Order': 'Sipariş',
  'Order calculator': 'Sipariş hesaplayıcı',
  'Orders just under the free-shipping threshold go over it.': 'Ücretsiz kargo sınırının hemen altındaki siparişler sınırı geçsin.',
  'Packaging': 'Paketleme',
  'Pay': 'Öde',
  'Pays off even if nobody changes': 'Kimse değişmese de kazandırır',
  'Per desi': 'Desi başı',
  'Per unit': 'Adet başı',
  'Pick a campaign type and one of its numbers, and see every value side by side. The small figures are the change in profit against no campaign, and what the customer saves.': 'Bir kampanya türü ve değerlerinden birini seçin, tüm değerleri yan yana görün. Küçük rakamlar kampanyasız duruma göre kâr farkını ve müşterinin kazancını gösterir.',
  'Pieces': 'Adet',
  'Platform commission': 'Platform komisyonu',
  'Platform commission {p}': 'Platform komisyonu {p}',
  'Presets': 'Hazır seçenekler',
  'Price {p} TL': 'Fiyat {p} TL',
  'Product': 'Ürün',
  'Product campaigns': 'Ürün kampanyaları',
  'Product revenue': 'Ürün geliri',
  'Product total after all discounts': 'Tüm indirimlerden sonraki ürün tutarı',
  'Product {n}': 'Ürün {n}',
  'Products': 'Ürünler',
  'Products & costs': 'Ürünler ve maliyetler',
  'Profit': 'Kâr',
  'Profit · margin': 'Kâr · marj',
  'Profit ÷ what the customer pays, for an order of one product, with the campaigns that are on.': 'Kâr ÷ müşterinin ödediği tutar; tek ürünlü sipariş için, açık kampanyalarla.',
  'Put leftover units in the smallest box that fits (13 pcs = large + small). Off: whole large boxes only.': 'Artan adetleri sığdıkları en küçük kutuya koy (13 adet = büyük + küçük). Kapalıyken yalnızca tam büyük kutu.',
  'Qty': 'Adet',
  'Quantities': 'Adetler',
  'Quantity tiers': 'Adet kademeleri',
  'Reach free shipping': 'Ücretsiz kargoya ulaşma',
  'Remove': 'Kaldır',
  'Remove one': 'Bir tane azalt',
  'Remove step': 'Kademeyi kaldır',
  'Remove {p}?': '{p} kaldırılsın mı?',
  'Replace everything with the defaults?': 'Her şey varsayılanlarla değiştirilsin mi?',
  'Reset': 'Sıfırla',
  'Reset to defaults': 'Varsayılanlara dön',
  'Reset.': 'Sıfırlandı.',
  'Result': 'Sonuç',
  'Results': 'Sonuçlar',
  'Revenue': 'Gelir',
  'Revenue calculator': 'Gelir hesaplayıcı',
  'Room for {n} more in the same box.': 'Aynı kutuya {n} adet daha sığar.',
  'Runs on each selected product separately.': 'Seçili her ürüne ayrı ayrı uygulanır.',
  'Safest first (lowest break-even)': 'En güvenli önce (en düşük başa baş)',
  'Sale price': 'Satış fiyatı',
  'Sale price and cost include VAT.': 'Satış fiyatı ve maliyet KDV dahildir.',
  'Save': 'Kaydet',
  'Save and move data': 'Verileri kaydet ve taşı',
  'Save the campaigns that are on to compare them later on the Results tab.': 'Açık kampanyaları kaydedin, sonra Sonuçlar sekmesinde karşılaştırın.',
  'Saved in this browser': 'Bu tarayıcıya kaydedildi',
  'Saved scenarios': 'Kayıtlı senaryolar',
  'Saved: {list}.': 'Kaydedildi: {list}.',
  'Scenario comparison': 'Senaryo karşılaştırması',
  'Scenario {n}': 'Senaryo {n}',
  'Select the text below and copy it.': 'Aşağıdaki metni seçip kopyalayın.',
  'Share of orders by quantity': 'Adede göre sipariş payı',
  'Shipping VAT': "Kargo KDV'si",
  'Shipping and packaging are paid per box, so extra units in the same box cost you only the product. Offers that only start at a quantity ("3 or more") reward just the customers who buy more, and quantity-framed offers tend to lift sales more than a plain % off.': 'Kargo ve paketleme kutu başına ödenir; aynı kutudaki ek adetlerin maliyeti yalnızca üründür. Belirli bir adetten başlayan teklifler ("3 ve üzeri") yalnızca daha çok alanı ödüllendirir ve adet odaklı teklifler düz % indirimden daha çok satış getirme eğilimindedir.',
  'Shipping cost': 'Kargo maliyeti',
  'Shipping fee': 'Kargo ücreti',
  'Shipping fee from customer': 'Müşteriden alınan kargo ücreti',
  'Shipping fee to customer': 'Müşteriye kargo ücreti',
  'Shipping tariff': 'Kargo tarifesi',
  'Show more ({n} left)': 'Daha fazla göster ({n} kaldı)',
  'Showing results with test prices. The small figures show the change from your saved prices.': 'Sonuçlar deneme fiyatlarıyla gösteriliyor. Küçük rakamlar kayıtlı fiyatlara göre farkı gösterir.',
  'Small': 'Küçük',
  'Step': 'Adım',
  'TL off': 'TL indirim',
  'TL off each unit': 'Adet başı TL indirim',
  'TL off the cart': 'Sepette TL indirim',
  'TL per shipment by total desi, VAT and EPH excluded. Tick "per desi" for rows priced per desi.': 'Toplam desiye göre gönderi başı TL, KDV ve EPH hariç. Desi başı fiyatlanan satırlar için "desi başı" işaretleyin.',
  'Target order': 'Hedef sipariş',
  'Test price for {p}': '{p} için deneme fiyatı',
  'Test prices': 'Deneme fiyatları',
  'That is not saved calculator data. Use a file or text made with Export.': 'Bu kayıtlı hesaplayıcı verisi değil. Dışa aktarma ile oluşturulan dosyayı veya metni kullanın.',
  'The box is full. One more unit ships as {b}.': 'Kutu dolu. Bir adet daha eklenirse {b} ile gönderilir.',
  'The download was not saved.': 'İndirme kaydedilmedi.',
  'The same orders under your saved scenarios. The most profitable one for each quantity is marked.': 'Aynı siparişler kayıtlı senaryolarınızla. Her adet için en kârlı olan işaretlidir.',
  'The second product usually ships in the same box, so almost all of its margin is extra profit. A small discount on the add-on, or a cart reward that the pair unlocks, gives a reason to add it.': 'İkinci ürün genelde aynı kutuyla gider; marjının neredeyse tamamı ek kârdır. Ek ürüne küçük bir indirim ya da ikisiyle açılan bir sepet ödülü, eklemek için sebep verir.',
  'This browser is not saving. Export a file to keep your data.': 'Bu tarayıcı kaydetmiyor. Verilerinizi korumak için dosyaya aktarın.',
  'This order loses money.': 'Bu sipariş zarar ettiriyor.',
  'Tick a pair to let them apply to the same order. When campaigns clash, the customer gets the combination that saves them the most.': 'Aynı siparişte birlikte uygulanabilmeleri için ikiliyi işaretleyin. Kampanyalar çakışırsa müşteriye en çok kazandıran kombinasyon uygulanır.',
  'To': 'Bitiş',
  'Total costs': 'Toplam maliyet',
  'Try a range': 'Aralık dene',
  'Try it': 'Dene',
  'Turn on two or more campaigns to choose which ones stack.': 'Hangilerinin birlikte uygulanacağını seçmek için en az iki kampanya açın.',
  'Turn on {name}': '{name} kampanyasını aç',
  'Turned on: {list}. Open Results to see it everywhere.': "Açıldı: {list}. Her yerde görmek için Sonuçlar'ı açın.",
  'Type': 'Tür',
  'Unit {q} takes the order from {a} to {b} desi. Shipping and packaging go up by {x} TL.': '{q}. adet siparişi {a} desiden {b} desiye çıkarır. Kargo ve paketleme {x} TL artar.',
  'Up to': 'En fazla',
  'VAT': 'KDV',
  'VAT included': 'KDV dahil',
  'VAT inside commission': 'Komisyondaki KDV',
  'VAT inside packaging': 'Paketlemedeki KDV',
  'VAT on this order (tracked separately)': "Bu siparişin KDV'si (ayrıca takip edilir)",
  'VAT payable': 'Ödenecek KDV',
  'VAT rate': 'KDV oranı',
  'Values tried': 'Denenen değerler',
  'Where the money goes': 'Para nereye gidiyor',
  'Where your costs jump for {p}': '{p} için maliyetin sıçradığı noktalar',
  'Which campaigns stack': 'Hangi kampanyalar birlikte uygulanır',
  'Why it works': 'Neden işe yarar',
  'Win more orders': 'Daha çok sipariş',
  'Without a discount, orders reach free shipping from {q} pcs. A discount on that order can drop it below the threshold, and the customer pays shipping again.': 'İndirimsiz siparişler {q} adetten itibaren ücretsiz kargoya ulaşır. Bu siparişe yapılan indirim tutarı sınırın altına düşürebilir ve müşteri yine kargo öder.',
  'X pieces for a price': 'X adet sabit fiyata',
  'Your prices include VAT. Of what the customer pays, {out} TL is VAT you collect for the state. You also paid {inp} TL VAT on goods, shipping, packaging and commission. The difference, {d} TL, is what you pay in your VAT return.': "Fiyatlarınız KDV dahildir. Müşterinin ödediğinin {out} TL'si devlet adına topladığınız KDV'dir. Ürün, kargo, paketleme ve komisyon için de {inp} TL KDV ödediniz. Aradaki fark, {d} TL, KDV beyannamesinde ödediğiniz tutardır.",
  'Zone': 'Bölge',
  'best': 'en iyi',
  'cart': 'sepet',
  'fill {box}': '{box} kutuyu doldur',
  'free': 'ücretsiz',
  'from {q} pcs': '{q} adetten itibaren',
  'list': 'liste',
  'no cost': 'maliyet yok',
  'not with': 'birlikte değil:',
  'order': 'sipariş',
  'pcs': 'adet',
  'per unit': 'adet başı',
  'saves {p}': '{p} kazanç',
  'tariff': 'tarife',
  '{a} TL off each': 'Adet başı {a} TL indirim',
  '{n} campaigns': '{n} kampanya',
  '{n} ideas': '{n} fikir',
  '{n} on': '{n} açık',
  '{n} pcs': '{n} adet',
  '{n} pcs or more': '{n} adet ve üzeri',
  '{n}. unit {p} off': '{n}. adete {p} indirim',
  '{p} more orders': '{p} daha fazla sipariş',
  '{p} of customers (1 in {n})': 'müşterilerin {p} kadarı ({n} kişide 1)',
  '{p} off': '{p} indirim',
  '{p} off carts over {a} TL': '{a} TL üzeri sepete {p} indirim',
  '{q} for {p} TL': '{q} adet {p} TL',
  '{v} TL off carts over {a} TL': '{a} TL üzeri sepete {v} TL indirim',
  '{v} pts': '{v} puan',
  '{x} TL more and shipping is free for the customer.': '{x} TL daha eklenirse kargo müşteriye ücretsiz olur.',
  "Sales channel": "Satış kanalı",
  "Trendyol tariffs": "Trendyol tarifeleri",
  "Pick a campaign type and one of its numbers to see the margin for every value. Below each margin is the profit change against no campaign; hover a cell for the details.": "Bir kampanya türü ve değerlerinden birini seçin, her değer için marjı görün. Marjın altındaki rakam kampanyasız duruma göre kâr farkıdır; ayrıntı için hücrenin üzerine gelin.",
  "none": "kampanyasız",
  "Sale price and cost include VAT. Prices are for {channel}; costs are shared by all channels.": "Satış fiyatı ve maliyet KDV dahildir. Fiyatlar {channel} içindir; maliyetler tüm kanallarda ortaktır.",
  "Barcode": "Barkod",
  "Boxes and packaging · {channel}": "Kutular ve paketleme · {channel}",
  "Fees and VAT · {channel}": "Ücretler ve KDV · {channel}",
  "Shipping tariff · {channel}": "Kargo tarifesi · {channel}",
  "saved prices": "kayıtlı fiyatlar",
  "no campaign": "kampanyasız",
  "Margin = profit ÷ what the customer pays. Profit is after commission, shipping, packaging and cost of goods.": "Marj = kâr ÷ müşterinin ödediği tutar. Kâr; komisyon, kargo, paketleme ve ürün maliyeti düşüldükten sonrakidir.",
  "Products in the chart": "Grafikteki ürünler",
  "Dashed: saved prices": "Kesikli: kayıtlı fiyatlar",
  "Dashed: no campaign": "Kesikli: kampanyasız",
  "Order fee": "Sipariş ücreti",
  "Imported {n} products for {period}.": "{period} için {n} ürün yüklendi.",
  "{n} new products were added. Enter their cost below.": "{n} yeni ürün eklendi. Maliyetlerini aşağıya girin.",
  "This is not a Trendyol commission tariff file. Download it from Trendyol (Komisyon Tarifeleri) and import the .xlsx as it is.": "Bu bir Trendyol komisyon tarifesi dosyası değil. Dosyayı Trendyol'dan (Komisyon Tarifeleri) indirip .xlsx olarak olduğu gibi yükleyin.",
  "Trendyol prices updated. Switch to Trendyol at the top to see results with them.": "Trendyol fiyatları güncellendi. Bu fiyatlarla sonuçları görmek için üstten Trendyol'u seçin.",
  "Saved. Check the new prices, pick the tariff in Trendyol, then upload the file there.": "Kaydedildi. Yeni fiyatları kontrol edin, Trendyol'da tarifeyi seçin ve dosyayı oraya yükleyin.",
  "commission": "komisyon",
  "profit": "kâr",
  "Commission tariff": "Komisyon tarifesi",
  "Import the weekly \"Komisyon Tarifeleri\" file from Trendyol. For each product you see your margin at today's price and at the top price of each commission band, using the Trendyol costs in Products & costs.": "Trendyol'un haftalık \"Komisyon Tarifeleri\" dosyasını yükleyin. Her ürün için bugünkü fiyatta ve her komisyon bandının en yüksek fiyatında marjınızı görürsünüz; Ürünler ve maliyetler'deki Trendyol maliyetleri kullanılır.",
  "Import tariff file": "Tarife dosyası yükle",
  "No tariff imported yet.": "Henüz tarife yüklenmedi.",
  "{n} products": "{n} ürün",
  "Order of": "Sipariş",
  "Average margin": "Ortalama marj",
  "today": "bugün",
  "chosen": "seçilen",
  "Choose the best for all": "Hepsinde en iyiyi seç",
  "Some products have no cost yet, so their margin is too high. Enter the cost in the table.": "Bazı ürünlerin maliyeti henüz yok, bu yüzden marjları olduğundan yüksek görünüyor. Maliyeti tabloya girin.",
  "Today": "Bugün",
  "The highest price that still gets this band's commission.": "Bu bandın komisyonunu alan en yüksek fiyat.",
  "Band {n}": "{n}. bant",
  "Use the chosen prices for Trendyol": "Seçilen fiyatları Trendyol için kullan",
  "Import the file again in this session to export it.": "Dışa aktarmak için dosyayı bu oturumda yeniden yükleyin.",
  "Export tariff file with new prices": "Yeni fiyatlarla tarife dosyasını indir",
  "The export fills the \"YENİ TSF\" column for products where you picked a new price, and leaves the rest of the file as it was. Choose the tariff in Trendyol as usual.": "Dışa aktarma, yeni fiyat seçtiğiniz ürünlerde \"YENİ TSF\" sütununu doldurur ve dosyanın geri kalanını olduğu gibi bırakır. Tarifeyi Trendyol'da her zamanki gibi seçin.",
  "Tariff history": "Tarife geçmişi",
  "Every file you import is kept here. With a few weeks of files you can see how the band limits move when your price changes.": "Yüklediğiniz her dosya burada saklanır. Birkaç haftalık dosyayla, fiyatınız değiştiğinde bant sınırlarının nasıl hareket ettiğini görebilirsiniz.",
  "In the latest file, the highest-commission band starts on average at {p} of your list price (from {lo} to {hi}). Below that price the commission drops.": "Son dosyada en yüksek komisyonlu bant, ortalama olarak liste fiyatınızın {p} kadarından başlıyor ({lo} ile {hi} arası). Bu fiyatın altında komisyon düşüyor.",
  "Import next week's file too. With two or more weeks this shows whether the band limits follow your price.": "Gelecek haftanın dosyasını da yükleyin. İki veya daha fazla haftayla, bant sınırlarının fiyatınızı izleyip izlemediği görülür.",
  "Your prices did not change between these files, so there is nothing to compare yet.": "Bu dosyalar arasında fiyatlarınız değişmemiş, bu yüzden henüz karşılaştırılacak bir şey yok.",
  "When your price changed, the band limits moved the same way in {a} of {b} cases.": "Fiyatınız değiştiğinde bant sınırları {b} durumun {a} tanesinde aynı yönde hareket etti.",
  "The limits seem to follow your own price, so a price cut can lower next week's limits too.": "Sınırlar kendi fiyatınızı izliyor gibi görünüyor; yani bir fiyat indirimi gelecek haftanın sınırlarını da düşürebilir.",
  "The limits do not seem to follow your own price closely.": "Sınırlar kendi fiyatınızı yakından izlemiyor gibi görünüyor.",
  "Week": "Hafta",
  "Highest band starts at": "En yüksek bant başlangıcı",
  "{p} of list price": "liste fiyatının {p} kadarı",
  "Remove this week?": "Bu hafta kaldırılsın mı?",
  "On products after discounts. Products with a commission tariff use it instead.": "İndirimlerden sonraki ürün tutarı üzerinden. Komisyon tarifesi olan ürünlerde tarife kullanılır.",
  "Fee per order": "Sipariş başı ücret",
  "Fixed platform fee per order, VAT included": "Sipariş başına sabit platform ücreti, KDV dahil",
  "Also sold on": "Şurada da satılıyor",
  "Remove {p} from {channel}?": "{p}, {channel} kanalından kaldırılsın mı?",
  "The customer sees a promotion price now. This price only applies if you leave the promotion.": "Müşteri şu an promosyon fiyatını görüyor. Bu fiyat yalnızca promosyondan çıkarsanız geçerli olur.",
  "without promotion": "promosyon olmadan",
  "Only for the separate VAT figure; profit does not change": "Yalnızca ayrı gösterilen KDV hesabı için; kârı değiştirmez",
  "Compare": "Karşılaştır",
  "Monthly": "Aylık plan",
  "Not saving": "Kaydedilmiyor",
  "{box} box": "{box} kutu",
  "Several boxes": "Birden çok kutu",
  "What to compare": "Neler karşılaştırılsın",
  "Pick up to {n}. A combination is a set of campaigns that run together, with the combination rules from the campaigns panel.": "En fazla {n} tane seçin. Kombinasyon, birlikte çalışan kampanyalardan oluşur; birleştirme kuralları kampanyalar panelinden gelir.",
  "No campaigns are on.": "Açık kampanya yok.",
  "New combination": "Yeni kombinasyon",
  "Choose campaigns from your list": "Listenizden kampanya seçin",
  "Name (optional)": "Ad (isteğe bağlı)",
  "Save and compare": "Kaydet ve karşılaştır",
  "Add campaigns in the campaigns panel first; they do not need to be on.": "Kampanyaları önce kampanyalar panelinde ekleyin; açık olmaları gerekmez.",
  "Pick at least two things to compare.": "Karşılaştırmak için en az iki seçenek seçin.",
  "Which one is stronger where": "Hangisi nerede daha güçlü",
  "Orders of one product, grouped by the box they ship in. Each card shows who has the best average {m} in that range.": "Tek ürünlü siparişler, gönderildikleri kutuya göre gruplanır. Her kart o aralıkta ortalama {m} en iyi olanı gösterir.",
  "margin": "marjı",
  "No difference between {a} and {b} here.": "Burada {a} ile {b} arasında fark yok.",
  "Average {v}": "Ortalama {v}",
  "over {b}": "{b} karşısında",
  "Best at {a} of {b} order sizes": "{b} sipariş adedinin {a} tanesinde en iyi",
  "Every order size": "Her sipariş adedi",
  "The best one for each size is marked. Hover a cell for what the customer pays.": "Her adet için en iyisi işaretlidir. Müşterinin ne ödediğini görmek için hücrenin üzerine gelin.",
  "Mixed orders: who wins": "Karışık siparişler: kim kazanıyor",
  "Every mix of two products in one order. The colour and number show which one gives the best {m}; hover for the figures.": "İki ürünün tek siparişteki her kombinasyonu. Renk ve numara en iyi {m} vereni gösterir; rakamlar için üzerine gelin.",
  "\"=\" means the top two are equal there.": "\"=\" ilk ikisinin orada eşit olduğunu gösterir.",
  "VAT is left out of profit (Products & costs).": "KDV kâra dahil değil (Ürünler ve maliyetler).",
  "Profit includes VAT; a credit counts as money back.": "Kâr KDV'yi içerir; devreden KDV geri gelen para sayılır.",
  "Profit includes VAT owed; a credit counts as lost.": "Kâr ödenecek KDV'yi içerir; devreden KDV kayıp sayılır.",
  "Orders per month": "Aylık sipariş",
  "Customers pay": "Müşterilerin ödediği",
  "Profit per month": "Aylık kâr",
  "VAT credit (devreden KDV)": "Devreden KDV",
  "VAT to pay": "Ödenecek KDV",
  "{n} orders": "{n} sipariş",
  "Uses the campaigns that are on.": "Açık kampanyalar kullanılır.",
  "Typical orders": "Tipik siparişler",
  "What a normal month looks like: each row is a kind of order and how many of them you get. Rows can mix two products.": "Normal bir ay: her satır bir sipariş türü ve ayda kaç tane geldiği. Bir satırda iki ürün olabilir.",
  "+ second product": "+ ikinci ürün",
  "Per month": "Aylık",
  "Profit per order": "Sipariş başı kâr",
  "Costs that are not per box": "Kutu başı olmayan maliyetler",
  "Ad spend per order": "Sipariş başı reklam",
  "Returns": "İadeler",
  "Return rate": "İade oranı",
  "of orders": "siparişlerin",
  "Cost per return": "İade başı maliyet",
  "return": "iade",
  "Cost per return: both shipping legs, packaging and any product you cannot resell.": "İade başı maliyet: gidiş-dönüş kargo, paketleme ve yeniden satılamayan ürün.",
  "Fixed costs per month (VAT included)": "Aylık sabit maliyetler (KDV dahil)",
  "Amount": "Tutar",
  "New cost": "Yeni maliyet",
  "Add fixed cost": "Sabit maliyet ekle",
  "The month in numbers": "Rakamlarla ay",
  "Ads": "Reklam",
  "Fixed costs": "Sabit maliyetler",
  "Profit before VAT": "KDV öncesi kâr",
  "VAT collected (sales)": "Tahsil edilen KDV (satışlar)",
  "VAT paid (purchases and services)": "Ödenen KDV (alımlar ve hizmetler)",
  "VAT credit carried forward": "Devreden KDV",
  "You pay more VAT than you collect: about {m} TL a month, {y} TL a year.": "Tahsil ettiğinizden fazla KDV ödüyorsunuz: ayda yaklaşık {m} TL, yılda {y} TL.",
  "Your products sell at a low VAT rate, while shipping, packaging and services carry 20%. The excess is carried forward as devreden KDV. Businesses selling at reduced rates can usually claim it back in cash above a yearly minimum; ask your accountant which applies to you, then pick the matching option in Products & costs.": "Ürünleriniz düşük KDV oranıyla satılıyor, kargo, paketleme ve hizmetler ise %20 KDV'li. Aradaki fark devreden KDV olarak sonraki aylara aktarılır. İndirimli oranla satış yapan işletmeler bu tutarı genellikle yıllık bir alt sınırın üzerinde nakden iade alabilir; hangisinin size uyduğunu muhasebecinize sorun ve Ürünler ve maliyetler'de uygun seçeneği işaretleyin.",
  "VAT you owe for this order: {x} TL": "Bu sipariş için ödenecek KDV: {x} TL",
  "VAT credit from this order: {x} TL": "Bu siparişten doğan devreden KDV: {x} TL",
  "Of what the customer pays, {out} TL is VAT you collect for the state (sale VAT). You paid {inp} TL VAT on the goods, shipping, packaging and commission.": "Müşterinin ödediğinin {out} TL'si devlet adına tahsil ettiğiniz KDV'dir (satış KDV'si). Ürün, kargo, paketleme ve komisyon için {inp} TL KDV ödediniz.",
  "You collected more than you paid, so {d} TL goes to the state in your VAT return.": "Ödediğinizden fazla tahsil ettiniz; {d} TL KDV beyannamesiyle devlete ödenir.",
  "You paid {d} TL more than you collected. That is VAT credit (devreden KDV): it lowers what you owe in later months, or can be claimed back.": "Tahsil ettiğinizden {d} TL fazla ödediniz. Bu devreden KDV'dir: sonraki aylarda ödeyeceğiniz KDV'den düşülür ya da iade talep edilebilir.",
  "It is not in the profit above. You can change that in Products & costs.": "Yukarıdaki kâra dahil değil. Bunu Ürünler ve maliyetler'den değiştirebilirsiniz.",
  "The profit above includes it.": "Yukarıdaki kâra dahildir.",
  "The profit above treats the credit as lost.": "Yukarıdaki kâr, devreden KDV'yi kayıp sayar.",
  "Add the {n} Mesh Stick products with their Shopify prices?": "{n} Mesh Stick ürünü Shopify fiyatlarıyla eklensin mi?",
  "Products you already have (same SKU) are skipped. Costs start at 0.": "Zaten olan ürünler (aynı SKU) atlanır. Maliyetler 0 olarak başlar.",
  "Add Mesh Stick products": "Mesh Stick ürünlerini ekle",
  "{n} products have no cost yet, so their margin reads too high.": "{n} ürünün henüz maliyeti yok; marjları olduğundan yüksek görünür.",
  "Cost for all of them": "Hepsi için maliyet",
  "Set for all without cost": "Maliyeti olmayanların hepsine uygula",
  "Sale VAT": "Satış KDV'si",
  "Purchase VAT": "Alış KDV'si",
  "VAT in profit": "Kârda KDV",
  "Leave VAT out of profit. Prices and costs count as paid; VAT is shown separately.": "KDV'yi kâra katma. Fiyat ve maliyetler ödendiği gibi sayılır; KDV ayrıca gösterilir.",
  "VAT is settled and credit comes back. VAT you owe lowers profit; excess VAT you paid (devreden KDV) raises it, because you get it refunded or use it later.": "KDV mahsup edilir ve devreden geri gelir. Ödenecek KDV kârı düşürür; fazla ödenen KDV (devreden KDV) iade alındığı ya da sonra kullanıldığı için kârı artırır.",
  "VAT is settled but credit is lost. VAT you owe lowers profit; excess VAT you paid is never recovered.": "KDV mahsup edilir ama devreden kaybolur. Ödenecek KDV kârı düşürür; fazla ödenen KDV hiç geri alınmaz.",
  "no fixed costs": "sabit maliyet yok",
  "never": "yok",
  "No second product": "İkinci ürün yok",
  "Products you already have (same SKU) are kept; only their box size is filled in if it is still 1. Costs start at 0.": "Zaten olan ürünler (aynı SKU) korunur; kutu yeri hâlâ 1 ise yalnızca o güncellenir. Maliyetler 0 olarak başlar.",
  "Shopify invoices from abroad without Turkish VAT, so 0. Only for the separate VAT figure.": "Shopify yurt dışından Türk KDV'si olmadan faturalar, bu yüzden 0. Yalnızca ayrı gösterilen KDV hesabı için.",
};
